CREATE TABLE conversations (
  id SERIAL PRIMARY KEY
  , user_id INTEGER NOT NULL REFERENCES users(id)
  ON DELETE CASCADE
  , message TEXT NOT NULL
  , created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);